# Generated by Django 4.2.18 on 2025-02-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_hotels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.CharField(default='https://tinyurl.com/bdf5yt5j', max_length=240),
            preserve_default=False,
        ),
    ]
