# Generated by Django 4.2.19 on 2025-02-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_hotelgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='users.movies')),
            ],
        ),
    ]
